// TARGET: aidev src/runners/local-runner.ts

import type { AgentContext, FileBlob } from "../core/types";
import { runSpecLint } from "../agents/spec-lint.agent";
import { runPRSynthesis } from "../agents/pr-synthesis.agent";
import { runThreatSketch } from "../agents/threat-sketch.agent";

export async function runLocalDemo(): Promise<string> {
  const changedFiles: FileBlob[] = [
    {
      path: "docs/example.md",
      content: "# Example\n\nThis is a demo file for the devkit.\n",
    },
  ];

  const ctx: AgentContext = {
    repo: { owner: "local", name: "the-thesis-chain-ai-devkit" },
    diffSummary: "Demo diff: add docs/example.md",
    changedFiles,
    promptVersion: "1.0.0",
  };

  const reports = [];
  reports.push(await runThreatSketch(ctx));
  reports.push(await runSpecLint(ctx));
  reports.push(await runPRSynthesis(ctx));

  return renderMarkdown(reports);
}

function renderMarkdown(reports: Array<{ agent: string; findings: any[] }>): string {
  const lines: string[] = [];
  lines.push("## AI Devkit Demo (Advisory)");
  lines.push("");
  lines.push("This report is generated by a schema-gated, stub-provider pipeline.");
  lines.push("");

  for (const r of reports) {
    lines.push(`### ${r.agent}`);
    for (const f of r.findings) {
      lines.push(`- **${String(f.severity).toUpperCase()}** [${f.category}] ${f.claim}`);
    }
    lines.push("");
  }

  return lines.join("\n");
}
